*&---------------------------------------------------------------------*
*& Objeto:   ZHOLA
*& Paquete:  $TMP
*&---------------------------------------------------------------------*
CLASS ZHOLA DEFINITION PUBLIC.
  PUBLIC SECTION.
    METHODS: constructor.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS ZHOLA IMPLEMENTATION.
  METHOD constructor.
    super->constructor( ).
  ENDMETHOD.
ENDCLASS.
